-- WMS Acatlán - esquema inicial PostgreSQL
CREATE TYPE user_role AS ENUM ('ADMIN','SUPERVISOR','RECEPCION','CALIDAD','SURTIDOR','CONTADOR','CONSULTA');
CREATE TYPE inventory_status AS ENUM ('PENDIENTE_CALIDAD','LIBERADO','BLOQUEADO_CALIDAD','BLOQUEADO_CADUCIDAD','EN_CONTEO');
CREATE TABLE users(id bigserial PRIMARY KEY,name text NOT NULL,username text UNIQUE NOT NULL,password_hash text NOT NULL,role user_role NOT NULL,active boolean DEFAULT true);
CREATE TABLE products(id bigserial PRIMARY KEY,sku text UNIQUE NOT NULL,description text NOT NULL,base_unit text DEFAULT 'PIEZA',pieces_per_pallet integer,life_days integer NOT NULL DEFAULT 245,category text,active boolean DEFAULT true);
CREATE TABLE clients(id bigserial PRIMARY KEY,code text UNIQUE NOT NULL,name text NOT NULL,min_life_days integer NOT NULL DEFAULT 245,active boolean DEFAULT true);
CREATE TABLE locations(id bigserial PRIMARY KEY,warehouse text NOT NULL DEFAULT 'ACATLAN',code text UNIQUE NOT NULL,rack text,position integer,level integer,capacity_pallets integer NOT NULL,status text NOT NULL DEFAULT 'DISPONIBLE');
CREATE TABLE receipts(id bigserial PRIMARY KEY,folio text UNIQUE NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),user_id bigint REFERENCES users,notes text,status text NOT NULL DEFAULT 'BORRADOR');
CREATE TABLE receipt_lines(id bigserial PRIMARY KEY,receipt_id bigint REFERENCES receipts,product_id bigint REFERENCES products,lot text NOT NULL,production_date date NOT NULL,expiry_date date NOT NULL,pieces integer NOT NULL CHECK(pieces>0),pieces_per_pallet_snapshot integer NOT NULL);
CREATE TABLE inventory(id bigserial PRIMARY KEY,product_id bigint REFERENCES products,lot text NOT NULL,production_date date,expiry_date date NOT NULL,location_id bigint REFERENCES locations,status inventory_status NOT NULL,pieces integer NOT NULL DEFAULT 0,reserved_pieces integer NOT NULL DEFAULT 0,UNIQUE(product_id,lot,location_id,status),CHECK(pieces>=0),CHECK(reserved_pieces>=0 AND reserved_pieces<=pieces));
CREATE TABLE movements(id bigserial PRIMARY KEY,movement_type text NOT NULL,product_id bigint REFERENCES products,lot text NOT NULL,from_location_id bigint REFERENCES locations,to_location_id bigint REFERENCES locations,pieces integer NOT NULL,reference_type text,reference_id bigint,user_id bigint REFERENCES users,created_at timestamptz DEFAULT now(),notes text);
CREATE TABLE orders(id bigserial PRIMARY KEY,delivery_reference text UNIQUE NOT NULL,sales_order text NOT NULL,client_id bigint REFERENCES clients,client_text text,scheduled_at timestamptz,imported_at timestamptz DEFAULT now(),status text NOT NULL DEFAULT 'IMPORTADO');
CREATE TABLE order_lines(id bigserial PRIMARY KEY,order_id bigint REFERENCES orders,product_id bigint REFERENCES products,requested_pieces integer NOT NULL,reserved_pieces integer DEFAULT 0,supplied_pieces integer DEFAULT 0,UNIQUE(order_id,product_id));
CREATE TABLE picklists(id bigserial PRIMARY KEY,folio text UNIQUE NOT NULL,order_id bigint REFERENCES orders,created_at timestamptz DEFAULT now(),taken_by bigint REFERENCES users,taken_at timestamptz,status text NOT NULL DEFAULT 'GENERADA');
CREATE TABLE picklist_lines(id bigserial PRIMARY KEY,picklist_id bigint REFERENCES picklists,order_line_id bigint REFERENCES order_lines,inventory_id bigint REFERENCES inventory,reserved_pieces integer NOT NULL,confirmed_pieces integer DEFAULT 0,incident_type text,notes text);
CREATE TABLE cycle_counts(id bigserial PRIMARY KEY,folio text UNIQUE NOT NULL,week_start date NOT NULL,status text NOT NULL DEFAULT 'GENERADO',created_by bigint REFERENCES users,approved_by bigint REFERENCES users);
CREATE TABLE cycle_count_lines(id bigserial PRIMARY KEY,count_id bigint REFERENCES cycle_counts,inventory_id bigint REFERENCES inventory,system_pieces integer NOT NULL,counted_pieces integer,difference integer,approved boolean DEFAULT false);
CREATE TABLE adjustments(id bigserial PRIMARY KEY,folio text UNIQUE NOT NULL,inventory_id bigint REFERENCES inventory,quantity_change integer NOT NULL,reason text NOT NULL,requested_by bigint REFERENCES users,approved_by bigint REFERENCES users,status text NOT NULL DEFAULT 'PENDIENTE',created_at timestamptz DEFAULT now());
